apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
        - name: basic-app
          image: "your-docker-image:latest"  # Replace this with the actual Docker image
          ports:
            - containerPort: 8080


